[package]
name = "mini-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version="1", feature=["full"] }
mini-redis = "0.4"
bytes = "1"

[[examplt]]
name = "hello-redis"
path = "examples/hello-redis.rs"